# Generated by Django 4.0.4 on 2022-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
